---
title: "dplyr and pipes"
output: html_notebook
---

# Manipulate data with dplyr and the pipe operator

```{r}
library(dplyr)
library(datasets) 

mtcars %>% 
  group_by(cyl, am) %>%
  select(mpg, cyl, wt, am) %>%
  summarise(avgmpg = mean(mpg), avgwt = mean(wt)) %>%
  filter(avgmpg > 20)

```
## Using functional sequences

```{r}
library(magrittr) # needed to include the pipe operators
library(lubridate)
read_year <- . %>% as.character %>% as.Date %>% year

# Creating a dataset
df <- data.frame(now = "2015-11-11", before = "2012-01-01")
#          now     before
# 1 2015-11-11 2012-01-01

# Example 1: applying `read_year` to a single character-vector
df$now %>% read_year
# [1] 2015

# Example 2: applying `read_year` to all columns of `df`
df %>% lapply(read_year) %>% as.data.frame  # implicit `lapply(df, read_year)
#    now before
# 1 2015   2012

# Example 3: same as above using `mutate_all`
library(dplyr)
df %>% mutate_all(funs(read_year))
# if an older version of dplyr use `mutate_each`
#    now before
# 1 2015   2012
```

## Assignment

```{r}
df <- df %>% select(1:3) %>% filter(mpg > 20, cyl == 6)

df %>% select(1:3) %>% filter(mpg > 20, cyl == 6) -> df

df %<>% select(1:3) %>% filter(mpg > 20, cyl == 6)

all_letters <- c(letters, LETTERS) %>%
    sort %T>% 
    write.csv(file = "all_letters.csv")

# %T>% (tee operator) allows you to forward a value into a side-effect-producing function while keeping the original lhs value intact. In other words: the tee operator works like %>%, except the return values is lhs itself, and not the result of the rhs function/expression
# 

library(ggplot2)
diamonds %>% 
    filter(depth > 60) %>% 
    group_by(cut) %>% 
    summarize(mean_price = mean(price)) %>% 
    ggplot(aes(x = cut, y = mean_price)) + 
        geom_bar(stat = "identity")



```

# BROOM
http://varianceexplained.org/r/broom-intro/

# Survival
https://github.com/pavopax/gists/blob/master/survival-in-R.md 
